USE Grupo1_BancoUCR;
GO

CREATE OR ALTER PROCEDURE SP_EliminarCliente @C_id_cliente INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Cliente WHERE C_id_cliente = @C_id_cliente;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarProducto @C_id_producto INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Producto WHERE C_id_producto = @C_id_producto;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarClienteProducto @C_id_cliente INT, @C_id_producto INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Cliente_Producto WHERE C_id_cliente = @C_id_cliente AND C_id_producto = @C_id_producto;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarTransaccion @C_id_transaccion INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Transaccion WHERE C_id_transaccion = @C_id_transaccion;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarTransferencia @C_id_transferencia INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Transferencia WHERE C_id_transferencia = @C_id_transferencia;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarCuentaVista @C_id_cuenta_vista INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Cuenta_Vista WHERE C_id_cuenta_vista = @C_id_cuenta_vista;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarCuentaPlanilla @C_id_cuenta_planilla INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Cuenta_Planilla WHERE C_id_cuenta_planilla = @C_id_cuenta_planilla;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarCuentaExpSimplificado @C_id_cuenta_expediente INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Cuenta_Expediente_Simplificado WHERE C_id_cuenta_expediente = @C_id_cuenta_expediente;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarPrestamo @C_id_prestamo INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Prestamo WHERE C_id_prestamo = @C_id_prestamo;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarLineaCredito @C_id_linea_credito INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Linea_Credito WHERE C_id_linea_credito = @C_id_linea_credito;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarTarjetaCredito @C_id_tarjeta INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Tarjeta_Credito WHERE C_id_tarjeta = @C_id_tarjeta;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarTarjetaDebito @C_id_tarjeta_debito INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Tarjeta_Debito WHERE C_id_tarjeta_debito = @C_id_tarjeta_debito;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarDepositoPlazo @C_id_deposito INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Deposito_Plazo WHERE C_id_deposito = @C_id_deposito;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarDepositoJudicial @C_id_deposito_judicial INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Deposito_Judicial WHERE C_id_deposito_judicial = @C_id_deposito_judicial;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarRemesa @C_id_remesa INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Remesa WHERE C_id_remesa = @C_id_remesa;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarCompraventaDivisa @C_id_compraventa INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Compraventa_Divisa WHERE C_id_compraventa = @C_id_compraventa;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarArrendamiento @C_id_arrendamiento INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Arrendamiento_Financiero WHERE C_id_arrendamiento = @C_id_arrendamiento;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarAvalGarantia @C_id_aval INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Aval_Garantia WHERE C_id_aval = @C_id_aval;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarFideicomiso @C_id_fideicomiso INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Fideicomiso WHERE C_id_fideicomiso = @C_id_fideicomiso;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarCajaSeguridad @C_id_caja INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Caja_Seguridad WHERE C_id_caja = @C_id_caja;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarCajeroAutomatico @C_id_cajero INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Cajero_Automatico WHERE C_id_cajero = @C_id_cajero;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarBancaLinea @C_id_banca_linea INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Banca_Linea WHERE C_id_banca_linea = @C_id_banca_linea;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_EliminarDescuentoFactura @C_id_descuento INT AS
BEGIN
    BEGIN TRY BEGIN TRANSACTION
        DELETE FROM Descuento_Factura WHERE C_id_descuento = @C_id_descuento;
    COMMIT TRANSACTION END TRY
    BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH
END;
GO
